package com.ahmedatef.reportingservice.enums;

public enum TransactionStatus {
    INITIATED, CARD_INVALID, ACCOUNT_BLOCKED, VALID, FRAUDULENT, FAILURE, SUCCESS, FRAUDULENT_NOTIFY_SUCCESS, FRAUDULENT_NOTIFY_FAILURE
}
